enum WorkflowStep {
  noWorkOrder,
  workOrderFound,
  startOdometer,
  preTripMedical,
  preTripMedicalWaiting,
  preTripMedicalRejected,
  preTripTechnical,
  preTripTechnicalWaiting,
  preTripTechnicalRejected,
  initialPrint,
  startShift,
  activeShift,
  finishOdometer,
  postTripMedical,
  postTripMedicalWaiting,
  postTripMedicalRejected,
  postTripTechnical,
  postTripTechnicalWaiting,
  postTripTechnicalRejected,
  finalPrint,
  closeShift,
  closed,
  cancelled;

  static WorkflowStep fromApi(String? value) {
    return switch (value) {
      'no_work_order' => WorkflowStep.noWorkOrder,
      'work_order_found' => WorkflowStep.workOrderFound,
      'start_odometer' => WorkflowStep.startOdometer,
      'pre_trip_medical' => WorkflowStep.preTripMedical,
      'pre_trip_medical_waiting' => WorkflowStep.preTripMedicalWaiting,
      'pre_trip_medical_rejected' => WorkflowStep.preTripMedicalRejected,
      'pre_trip_technical' => WorkflowStep.preTripTechnical,
      'pre_trip_technical_waiting' => WorkflowStep.preTripTechnicalWaiting,
      'pre_trip_technical_rejected' => WorkflowStep.preTripTechnicalRejected,
      'initial_print' => WorkflowStep.initialPrint,
      'start_shift' => WorkflowStep.startShift,
      'active_shift' => WorkflowStep.activeShift,
      'finish_odometer' => WorkflowStep.finishOdometer,
      'post_trip_medical' => WorkflowStep.postTripMedical,
      'post_trip_medical_waiting' => WorkflowStep.postTripMedicalWaiting,
      'post_trip_medical_rejected' => WorkflowStep.postTripMedicalRejected,
      'post_trip_technical' => WorkflowStep.postTripTechnical,
      'post_trip_technical_waiting' => WorkflowStep.postTripTechnicalWaiting,
      'post_trip_technical_rejected' => WorkflowStep.postTripTechnicalRejected,
      'final_print' => WorkflowStep.finalPrint,
      'close_shift' => WorkflowStep.closeShift,
      'closed' => WorkflowStep.closed,
      'cancelled' => WorkflowStep.cancelled,
      _ => WorkflowStep.noWorkOrder,
    };
  }
}
